### ISSUE TITLE
try to deploy failed when building pages,error message:TypeError: Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by leapyear1969** [YunYouJun/valaxy#493]
### Describe the bug

```javascript
jason@jason:~/valaxy-blog$ npm run build

> valaxy-blog@0.0.0 build
> npm run build:ssg


> valaxy-blog@0.0.0 build:ssg
> valaxy build --ssg

✔ Resolve addons from /home/jason/valaxy-blog

  🌌 Valaxy  v0.22.4

  🪐 theme   > yun (v0.22.4)
  📁 /home/jason/valaxy-blog

✔ [HOOK] options:resolved done.
✔ [HOOK] config:init done.
✔ [HOOK] build:before done.

......
......
......

[vite-ssg] Rendering Pages... (11)
[vite-ssg] Critical CSS generation enabled via `beasties`
file:///home/jason/valaxy-blog/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1080
        throw new Error(`${gray("[vite-ssg]")} ${red(`Error on page: ${cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /page
TypeError: Cannot read properties of null (reading 'appendChild')
    at Beasties.embedLinkedStylesheet (file:///home/jason/valaxy-blog/node_modules/beasties/dist/index.mjs:706:23)
    at async Promise.all (index 0)
    at async Beasties.process (file:///home/jason/valaxy-blog/node_modules/beasties/dist/index.mjs:534:7)
    at async file:///home/jason/valaxy-blog/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1070:25
    at async file:///home/jason/valaxy-blog/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:714:36
    at file:///home/jason/valaxy-blog/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1080:15
    at async file:///home/jason/valaxy-blog/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:714:36

Node.js v20.12.0
jason@jason:~/valaxy-blog$ 
```

### Reproduction

prod

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 1.02 GB / 3.79 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.3.0 - ~/.local/share/pnpm/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Thanks. Fixed in `v0.22.5`.

**Comment by leapyear1969** [comment]
> Thanks. Fixed in `v0.22.5`.
> 
> Caused by `beasties` preload `document.body` in ssg.

@YunYouJun Just tested, still not working in v0.22.5-beta.4, same error. 

```shell
jason@jason:~/valaxy-blog$ pnpm run build

> valaxy-blog@0.0.0 build /home/jason/valaxy-blog
> npm run build:ssg


> valaxy-blog@0.0.0 build:ssg
> valaxy build --ssg

✔ Resolve addons from /home/jason/valaxy-blog

  🌌 Valaxy  v0.22.5-beta.4

  🪐 theme   > yun (v0.22.5-beta.4)
  📁 /home/jason/valaxy-blog

✔ [HOOK] options:resolved done.
✔ [HOOK] config:init done.
✔ [HOOK] build:before done.
...
...
...
vite-ssg] Rendering Pages... (11)
[vite-ssg] Critical CSS generation enabled via `beasties`
file:///home/jason/valaxy-blog/node_modules/.pnpm/vite-ssg@0.24.3_beasties@0.2.0_vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_sass@1.83.0_terser@5_u5eqq2mucsbpav3p4kfg4qvtku/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1080
        throw new Error(`${gray("[vite-ssg]")} ${red(`Error on page: ${cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /page
TypeError: Cannot read properties of null (reading 'appendChild')
    at Beasties.embedLinkedStylesheet (file:///home/jason/valaxy-blog/node_modules/.pnpm/beasties@0.2.0/node_modules/beasties/dist/index.mjs:706:23)
    at async Promise.all (index 0)
    at async Beasties.process (file:///home/jason/valaxy-blog/node_modules/.pnpm/beasties@0.2.0/node_modules/beasties/dist/index.mjs:534:7)
    at async file:///home/jason/valaxy-blog/node_modules/.pnpm/vite-ssg@0.24.3_beasties@0.2.0_vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_sass@1.83.0_terser@5_u5eqq2mucsbpav3p4kfg4qvtku/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1070:25
    at async file:///home/jason/valaxy-blog/node_modules/.pnpm/vite-ssg@0.24.3_beasties@0.2.0_vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_sass@1.83.0_terser@5_u5eqq2mucsbpav3p4kfg4qvtku/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:714:36
    at file:///home/jason/valaxy-blog/node_modules/.pnpm/vite-ssg@0.24.3_beasties@0.2.0_vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_sass@1.83.0_terser@5_u5eqq2mucsbpav3p4kfg4qvtku/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:1080:15
    at async file:///home/jason/valaxy-blog/node_modules/.pnpm/vite-ssg@0.24.3_beasties@0.2.0_vite@6.0.5_@types+node@22.10.2_jiti@2.4.2_sass@1.83.0_terser@5_u5eqq2mucsbpav3p4kfg4qvtku/node_modules/vite-ssg/dist/shared/vite-ssg.BMX3cKoj.mjs:714:36

Node.js v20.18.1
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by YunYouJun** [comment]
Hi, `beta` is for test, you can use `v0.22.5` directly.

**Comment by leapyear1969** [comment]
> Hi, `beta` is for test, you can use `v0.22.5` directly.

Thanks, it's woking with v0.22.5~ 👍
![image](https://github.com/user-attachments/assets/7824c574-9818-4106-9ba1-e7c6a6cb17d5)
